version: '3'
services:
  app:
    build: 
      context: app
      dockerfile: Dockerfile
    restart: on-failure
    container_name: faceitfinder
    command: npm start
    volumes: 
      - ./app:/usr/src/app
    env_file:
      - .env